# Generated by Django 3.0.7 on 2022-09-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dersler_ders_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='ders_seviyes',
            field=models.CharField(choices=[('Kolay', 'Kolay'), ('Orta', 'Orta'), ('Zor', 'Zor')], default='Orta', max_length=30),
        ),
    ]
