# Generated by Django 3.0.7 on 2022-09-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dersler_ders_seviyes'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.FileField(upload_to='tutorials/')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dersler')),
            ],
        ),
    ]
