# Generated by Django 3.0.7 on 2022-09-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorials'),
    ]

    operations = [
        migrations.CreateModel(
            name='konu_testleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ImageField(upload_to='questions/')),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dersler')),
            ],
        ),
    ]
