# Generated by Django 3.0.7 on 2022-09-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_konu_testleri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='konu_testleri',
            new_name='study_question',
        ),
    ]
