# Generated by Django 3.0.7 on 2022-09-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_test_answers_test_questions_testler'),
    ]

    operations = [
        migrations.CreateModel(
            name='winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_student', models.ImageField(upload_to='kazananlarımız/')),
                ('winner_student_name', models.CharField(max_length=100)),
                ('winner_student_uni', models.CharField(max_length=100)),
                ('winner_student_comment', models.CharField(max_length=500)),
            ],
        ),
    ]
