# Generated by Django 3.0.7 on 2022-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220907_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='winner_student',
            field=models.ImageField(upload_to='winners'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='winner_student_comment',
            field=models.TextField(),
        ),
    ]
