# Generated by Django 3.0.7 on 2022-09-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220908_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_answers',
            name='test',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.testler'),
            preserve_default=False,
        ),
    ]
